apiVersion: v1
kind: Pod
metadata:
  name: doppelganger-train
  labels:
    app: doppelganger-train
    type: training
    framework: tensorflow
spec:
  restartPolicy: OnFailure
  containers:
  - name: doppelganger-train
    image: antjebarth/doppelganger-train:1.0.0 
    imagePullPolicy: Always
    command:
      - "python"
      - "doppelganger-train.py"
      - "--model_export_path"
      - "s3://antje-doppelganger-data/model/tf_saved_model"
      - "--model_summary_path"
      - "s3://antje-doppelganger-data/model/tf_summary"
      - "--epochs"
      - "40"
    env:
      - name: AWS_REGION
        value: eu-central-1
